COMMENT =		C++ header-only HTTP/HTTPS server and client library

V =			0.18.0
PKGNAME =		cpp-httplib-${V}

DIST_TUPLE +=		github yhirose cpp-httplib v${V} .

CATEGORIES =		devel

HOMEPAGE =		https://github.com/yhirose/cpp-httplib

MAINTAINER =		"Ed <ed@i2pmail.org>"

# MIT
PERMIT_PACKAGE =	Yes

MODULES =		devel/cmake

BUILD_DEPENDS =		devel/cmake

NO_TEST =		Yes

PKG_ARCH =		*

.include <bsd.port.mk>
