COMMENT =		SQLite ORM light header only library for modern C++

V =			1.9
PKGNAME =		sqlite-orm-${V}

DIST_TUPLE +=		github fnc12 sqlite_orm v${V} .

CATEGORIES =		devel

HOMEPAGE =		https://github.com/fnc12/sqlite_orm

MAINTAINER =		"Ed <ed@i2pmail.org>"

# AGPLv3 (MIT if purchased)
PERMIT_PACKAGE =	Yes

COMPILER =		base-clang ports-gcc

MODULES =		devel/cmake

BUILD_DEPENDS =		devel/cmake

TEST_DEPENDS =		devel/catch2

PKG_ARCH =		*

.include <bsd.port.mk>
